### ISSUE TITLE
Login页面白屏

### ISSUE THREAD

**Issue by Aurorum-Studio** [albaz64/files.gallery#1]
Hello,
在config.php中设置用户名和密码后，加载网站时登录页会白屏，无法加载，用回官方的index.php后就不会，但是会被要求licence了，通过浏览器控制台查看没有发现问题，请问您可以看下有什么可能的原因吗，谢谢

**Comment by albaz64** [comment]
现在已经修复了，用最新的 index 代码可以正常工作。
是格式化之后产生的问题，原本是为了让代码有更好的可读性，但是看起来对于混杂 HTML 的 PHP 代码支持性并不好，如果后续还有问题我会回滚到格式化之前的版本。

**Comment by Aurorum-Studio** [comment]
试过新版本啦，登录页无法加载的情况已经解决了，谢谢呀
我就关闭这个issue咯，如果后面有什么问题再联系您🦊
